
server.port:
  9994

#curator zookeeper
curator.connectString : localhost:2181
curator.retryCount : 3
curator.elapsedTimeMs : 2000
curator.sessionTimeoutMs: 60000
curator.connectionTimeoutMs: 10000

#mysql 连接
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zookeeper?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=true
    username: root
    password: root
  #redis 连接配置
  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    #password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: -1 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 2 # 连接池中的最小空闲连接

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher





#全局设置主键生成策略
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:/xml/**/*.xml


# 自定义redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 60 # 验证码超期时间

