
server.port:
  9994

#curator zookeeper
curator.connectString : localhost:2181
curator.retryCount : 3
curator.elapsedTimeMs : 2000
curator.sessionTimeoutMs: 60000
curator.connectionTimeoutMs: 10000

#mysql 连接
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zookeeper?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=true
    username: root
    password: root
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1
  #redis 连接配置
  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    #password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: -1 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 2 # 连接池中的最小空闲连接

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher





#全局设置主键生成策略
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:/xml/**/*.xml


# 自定义redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 60 # 验证码超期时间

#定时任务配置参数
scheduled:
    task:
        cron: 0/20 * * * * ?


zookeeper:
  address: localhost:2181
  namespace: elastic-job
  connectionTimeout: 10000
  sessionTimeout: 10000
  maxRetries: 3


# simplejob配置
MySimpleJob:
  cron: 0/5 * * * * ?
  shardingTotalCount: 5
  shardingItemParameters: 0=java,1=php,2=erlang,3=angular,4=vue
  jobParameter: source1=public,source2=private
  failover: true
  monitorExecution: true
  monitorPort: 8889
  maxTimeDiffSeconds: -1
  jobShardingStrategyClass: com.dangdang.ddframe.job.lite.api.strategy.impl.AverageAllocationJobShardingStrategy

# simplejob配置
MySimpleJobOther:
  cron: 0/2 * * * * ?
  shardingTotalCount: 1
  shardingItemParameters: 0=java,1=php,2=erlang,3=angular,4=vue
  jobParameter: source1=public,source2=private
  failover: true
  monitorExecution: true
  monitorPort: 8889
  maxTimeDiffSeconds: -1
  jobShardingStrategyClass: com.dangdang.ddframe.job.lite.api.strategy.impl.AverageAllocationJobShardingStrategy



dataflowJob:
  cron: 0/10 * * * * ?
  shardingTotalCount: 2
  shardingItemParameters: 0=jinan,1=qingdao